/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazione.model.impl;

import prenotazione.model.Postazione;

import prenotazione.service.PostazioneLocalServiceUtil;

/**
 * The extended model base implementation for the Postazione service. Represents a row in the &quot;postazioni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PostazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PostazioneImpl
 * @see Postazione
 * @generated
 */
public abstract class PostazioneBaseImpl
	extends PostazioneModelImpl implements Postazione {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a postazione model instance should use the <code>Postazione</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PostazioneLocalServiceUtil.addPostazione(this);
		}
		else {
			PostazioneLocalServiceUtil.updatePostazione(this);
		}
	}

}