/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazione.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import prenotazione.model.Prenotazione;
import prenotazione.model.PrenotazioneModel;

/**
 * The base model implementation for the Prenotazione service. Represents a row in the &quot;prenotazioni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PrenotazioneModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PrenotazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PrenotazioneImpl
 * @generated
 */
@JSON(strict = true)
public class PrenotazioneModelImpl
	extends BaseModelImpl<Prenotazione> implements PrenotazioneModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prenotazione model instance should use the <code>Prenotazione</code> interface instead.
	 */
	public static final String TABLE_NAME = "prenotazioni";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"prenotazioneId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"email", Types.VARCHAR}, {"data", Types.TIMESTAMP},
		{"ora_inizio", Types.VARCHAR}, {"ora_fine", Types.VARCHAR},
		{"postazione_id", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("prenotazioneId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("data", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ora_inizio", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ora_fine", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postazione_id", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table prenotazioni (uuid_ VARCHAR(75) null,prenotazioneId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,email VARCHAR(75) null,data DATE null,ora_inizio VARCHAR(75) null,ora_fine VARCHAR(75) null,postazione_id VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table prenotazioni";

	public static final String ORDER_BY_JPQL =
		" ORDER BY prenotazione.prenotazioneId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY prenotazioni.prenotazioneId ASC";

	public static final String DATA_SOURCE = "prenotazioniDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRENOTAZIONEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PrenotazioneModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _prenotazioneId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPrenotazioneId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _prenotazioneId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Prenotazione.class;
	}

	@Override
	public String getModelClassName() {
		return Prenotazione.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Prenotazione, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Prenotazione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Prenotazione, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Prenotazione)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Prenotazione, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Prenotazione, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Prenotazione)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Prenotazione, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Prenotazione, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Prenotazione, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Prenotazione, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<Prenotazione, Object>>();

			attributeGetterFunctions.put("uuid", Prenotazione::getUuid);
			attributeGetterFunctions.put(
				"prenotazioneId", Prenotazione::getPrenotazioneId);
			attributeGetterFunctions.put("groupId", Prenotazione::getGroupId);
			attributeGetterFunctions.put(
				"companyId", Prenotazione::getCompanyId);
			attributeGetterFunctions.put("userId", Prenotazione::getUserId);
			attributeGetterFunctions.put("userName", Prenotazione::getUserName);
			attributeGetterFunctions.put(
				"createDate", Prenotazione::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Prenotazione::getModifiedDate);
			attributeGetterFunctions.put("email", Prenotazione::getEmail);
			attributeGetterFunctions.put("data", Prenotazione::getData);
			attributeGetterFunctions.put(
				"oraInizio", Prenotazione::getOraInizio);
			attributeGetterFunctions.put("oraFine", Prenotazione::getOraFine);
			attributeGetterFunctions.put(
				"postazioneId", Prenotazione::getPostazioneId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Prenotazione, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Prenotazione, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<Prenotazione, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<Prenotazione, String>)Prenotazione::setUuid);
			attributeSetterBiConsumers.put(
				"prenotazioneId",
				(BiConsumer<Prenotazione, Long>)
					Prenotazione::setPrenotazioneId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Prenotazione, Long>)Prenotazione::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Prenotazione, Long>)Prenotazione::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<Prenotazione, Long>)Prenotazione::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Prenotazione, String>)Prenotazione::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Prenotazione, Date>)Prenotazione::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Prenotazione, Date>)Prenotazione::setModifiedDate);
			attributeSetterBiConsumers.put(
				"email",
				(BiConsumer<Prenotazione, String>)Prenotazione::setEmail);
			attributeSetterBiConsumers.put(
				"data", (BiConsumer<Prenotazione, Date>)Prenotazione::setData);
			attributeSetterBiConsumers.put(
				"oraInizio",
				(BiConsumer<Prenotazione, String>)Prenotazione::setOraInizio);
			attributeSetterBiConsumers.put(
				"oraFine",
				(BiConsumer<Prenotazione, String>)Prenotazione::setOraFine);
			attributeSetterBiConsumers.put(
				"postazioneId",
				(BiConsumer<Prenotazione, String>)
					Prenotazione::setPostazioneId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPrenotazioneId() {
		return _prenotazioneId;
	}

	@Override
	public void setPrenotazioneId(long prenotazioneId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prenotazioneId = prenotazioneId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public Date getData() {
		return _data;
	}

	@Override
	public void setData(Date data) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_data = data;
	}

	@JSON
	@Override
	public String getOraInizio() {
		if (_oraInizio == null) {
			return "";
		}
		else {
			return _oraInizio;
		}
	}

	@Override
	public void setOraInizio(String oraInizio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oraInizio = oraInizio;
	}

	@JSON
	@Override
	public String getOraFine() {
		if (_oraFine == null) {
			return "";
		}
		else {
			return _oraFine;
		}
	}

	@Override
	public void setOraFine(String oraFine) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oraFine = oraFine;
	}

	@JSON
	@Override
	public String getPostazioneId() {
		if (_postazioneId == null) {
			return "";
		}
		else {
			return _postazioneId;
		}
	}

	@Override
	public void setPostazioneId(String postazioneId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_postazioneId = postazioneId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Prenotazione.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Prenotazione.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Prenotazione toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Prenotazione>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PrenotazioneImpl prenotazioneImpl = new PrenotazioneImpl();

		prenotazioneImpl.setUuid(getUuid());
		prenotazioneImpl.setPrenotazioneId(getPrenotazioneId());
		prenotazioneImpl.setGroupId(getGroupId());
		prenotazioneImpl.setCompanyId(getCompanyId());
		prenotazioneImpl.setUserId(getUserId());
		prenotazioneImpl.setUserName(getUserName());
		prenotazioneImpl.setCreateDate(getCreateDate());
		prenotazioneImpl.setModifiedDate(getModifiedDate());
		prenotazioneImpl.setEmail(getEmail());
		prenotazioneImpl.setData(getData());
		prenotazioneImpl.setOraInizio(getOraInizio());
		prenotazioneImpl.setOraFine(getOraFine());
		prenotazioneImpl.setPostazioneId(getPostazioneId());

		prenotazioneImpl.resetOriginalValues();

		return prenotazioneImpl;
	}

	@Override
	public Prenotazione cloneWithOriginalValues() {
		PrenotazioneImpl prenotazioneImpl = new PrenotazioneImpl();

		prenotazioneImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		prenotazioneImpl.setPrenotazioneId(
			this.<Long>getColumnOriginalValue("prenotazioneId"));
		prenotazioneImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		prenotazioneImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		prenotazioneImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		prenotazioneImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		prenotazioneImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		prenotazioneImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		prenotazioneImpl.setEmail(this.<String>getColumnOriginalValue("email"));
		prenotazioneImpl.setData(this.<Date>getColumnOriginalValue("data"));
		prenotazioneImpl.setOraInizio(
			this.<String>getColumnOriginalValue("ora_inizio"));
		prenotazioneImpl.setOraFine(
			this.<String>getColumnOriginalValue("ora_fine"));
		prenotazioneImpl.setPostazioneId(
			this.<String>getColumnOriginalValue("postazione_id"));

		return prenotazioneImpl;
	}

	@Override
	public int compareTo(Prenotazione prenotazione) {
		long primaryKey = prenotazione.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Prenotazione)) {
			return false;
		}

		Prenotazione prenotazione = (Prenotazione)object;

		long primaryKey = prenotazione.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Prenotazione> toCacheModel() {
		PrenotazioneCacheModel prenotazioneCacheModel =
			new PrenotazioneCacheModel();

		prenotazioneCacheModel.uuid = getUuid();

		String uuid = prenotazioneCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			prenotazioneCacheModel.uuid = null;
		}

		prenotazioneCacheModel.prenotazioneId = getPrenotazioneId();

		prenotazioneCacheModel.groupId = getGroupId();

		prenotazioneCacheModel.companyId = getCompanyId();

		prenotazioneCacheModel.userId = getUserId();

		prenotazioneCacheModel.userName = getUserName();

		String userName = prenotazioneCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			prenotazioneCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			prenotazioneCacheModel.createDate = createDate.getTime();
		}
		else {
			prenotazioneCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			prenotazioneCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			prenotazioneCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		prenotazioneCacheModel.email = getEmail();

		String email = prenotazioneCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			prenotazioneCacheModel.email = null;
		}

		Date data = getData();

		if (data != null) {
			prenotazioneCacheModel.data = data.getTime();
		}
		else {
			prenotazioneCacheModel.data = Long.MIN_VALUE;
		}

		prenotazioneCacheModel.oraInizio = getOraInizio();

		String oraInizio = prenotazioneCacheModel.oraInizio;

		if ((oraInizio != null) && (oraInizio.length() == 0)) {
			prenotazioneCacheModel.oraInizio = null;
		}

		prenotazioneCacheModel.oraFine = getOraFine();

		String oraFine = prenotazioneCacheModel.oraFine;

		if ((oraFine != null) && (oraFine.length() == 0)) {
			prenotazioneCacheModel.oraFine = null;
		}

		prenotazioneCacheModel.postazioneId = getPostazioneId();

		String postazioneId = prenotazioneCacheModel.postazioneId;

		if ((postazioneId != null) && (postazioneId.length() == 0)) {
			prenotazioneCacheModel.postazioneId = null;
		}

		return prenotazioneCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Prenotazione, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Prenotazione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Prenotazione, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Prenotazione)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Prenotazione>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Prenotazione.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _prenotazioneId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _email;
	private Date _data;
	private String _oraInizio;
	private String _oraFine;
	private String _postazioneId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Prenotazione, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Prenotazione)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("prenotazioneId", _prenotazioneId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("data", _data);
		_columnOriginalValues.put("ora_inizio", _oraInizio);
		_columnOriginalValues.put("ora_fine", _oraFine);
		_columnOriginalValues.put("postazione_id", _postazioneId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("ora_inizio", "oraInizio");
		attributeNames.put("ora_fine", "oraFine");
		attributeNames.put("postazione_id", "postazioneId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("prenotazioneId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("email", 256L);

		columnBitmasks.put("data", 512L);

		columnBitmasks.put("ora_inizio", 1024L);

		columnBitmasks.put("ora_fine", 2048L);

		columnBitmasks.put("postazione_id", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Prenotazione _escapedModel;

}