/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazione.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import prenotazione.model.Prenotazioni;
import prenotazione.model.PrenotazioniModel;

/**
 * The base model implementation for the Prenotazioni service. Represents a row in the &quot;Prenotazioni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PrenotazioniModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PrenotazioniImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PrenotazioniImpl
 * @generated
 */
@JSON(strict = true)
public class PrenotazioniModelImpl
	extends BaseModelImpl<Prenotazioni> implements PrenotazioniModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prenotazioni model instance should use the <code>Prenotazioni</code> interface instead.
	 */
	public static final String TABLE_NAME = "Prenotazioni";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"prenotazioneId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"email", Types.VARCHAR}, {"data_", Types.TIMESTAMP},
		{"oraInizio", Types.VARCHAR}, {"oraFine", Types.VARCHAR},
		{"postazioneId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("prenotazioneId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("data_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("oraInizio", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oraFine", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postazioneId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Prenotazioni (uuid_ VARCHAR(75) null,prenotazioneId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,email VARCHAR(75) null,data_ DATE null,oraInizio VARCHAR(75) null,oraFine VARCHAR(75) null,postazioneId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Prenotazioni";

	public static final String ORDER_BY_JPQL =
		" ORDER BY prenotazioni.prenotazioneId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Prenotazioni.prenotazioneId ASC";

	public static final String DATA_SOURCE = "prenotazioniDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRENOTAZIONEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PrenotazioniModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _prenotazioneId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPrenotazioneId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _prenotazioneId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Prenotazioni.class;
	}

	@Override
	public String getModelClassName() {
		return Prenotazioni.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Prenotazioni, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Prenotazioni, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Prenotazioni, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Prenotazioni)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Prenotazioni, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Prenotazioni, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Prenotazioni)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Prenotazioni, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Prenotazioni, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Prenotazioni, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Prenotazioni, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<Prenotazioni, Object>>();

			attributeGetterFunctions.put("uuid", Prenotazioni::getUuid);
			attributeGetterFunctions.put(
				"prenotazioneId", Prenotazioni::getPrenotazioneId);
			attributeGetterFunctions.put("groupId", Prenotazioni::getGroupId);
			attributeGetterFunctions.put(
				"companyId", Prenotazioni::getCompanyId);
			attributeGetterFunctions.put("userId", Prenotazioni::getUserId);
			attributeGetterFunctions.put("userName", Prenotazioni::getUserName);
			attributeGetterFunctions.put(
				"createDate", Prenotazioni::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Prenotazioni::getModifiedDate);
			attributeGetterFunctions.put("email", Prenotazioni::getEmail);
			attributeGetterFunctions.put("data", Prenotazioni::getData);
			attributeGetterFunctions.put(
				"oraInizio", Prenotazioni::getOraInizio);
			attributeGetterFunctions.put("oraFine", Prenotazioni::getOraFine);
			attributeGetterFunctions.put(
				"postazioneId", Prenotazioni::getPostazioneId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Prenotazioni, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Prenotazioni, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<Prenotazioni, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<Prenotazioni, String>)Prenotazioni::setUuid);
			attributeSetterBiConsumers.put(
				"prenotazioneId",
				(BiConsumer<Prenotazioni, Long>)
					Prenotazioni::setPrenotazioneId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Prenotazioni, Long>)Prenotazioni::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Prenotazioni, Long>)Prenotazioni::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<Prenotazioni, Long>)Prenotazioni::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Prenotazioni, String>)Prenotazioni::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Prenotazioni, Date>)Prenotazioni::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Prenotazioni, Date>)Prenotazioni::setModifiedDate);
			attributeSetterBiConsumers.put(
				"email",
				(BiConsumer<Prenotazioni, String>)Prenotazioni::setEmail);
			attributeSetterBiConsumers.put(
				"data", (BiConsumer<Prenotazioni, Date>)Prenotazioni::setData);
			attributeSetterBiConsumers.put(
				"oraInizio",
				(BiConsumer<Prenotazioni, String>)Prenotazioni::setOraInizio);
			attributeSetterBiConsumers.put(
				"oraFine",
				(BiConsumer<Prenotazioni, String>)Prenotazioni::setOraFine);
			attributeSetterBiConsumers.put(
				"postazioneId",
				(BiConsumer<Prenotazioni, String>)
					Prenotazioni::setPostazioneId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPrenotazioneId() {
		return _prenotazioneId;
	}

	@Override
	public void setPrenotazioneId(long prenotazioneId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prenotazioneId = prenotazioneId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public Date getData() {
		return _data;
	}

	@Override
	public void setData(Date data) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_data = data;
	}

	@JSON
	@Override
	public String getOraInizio() {
		if (_oraInizio == null) {
			return "";
		}
		else {
			return _oraInizio;
		}
	}

	@Override
	public void setOraInizio(String oraInizio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oraInizio = oraInizio;
	}

	@JSON
	@Override
	public String getOraFine() {
		if (_oraFine == null) {
			return "";
		}
		else {
			return _oraFine;
		}
	}

	@Override
	public void setOraFine(String oraFine) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oraFine = oraFine;
	}

	@JSON
	@Override
	public String getPostazioneId() {
		if (_postazioneId == null) {
			return "";
		}
		else {
			return _postazioneId;
		}
	}

	@Override
	public void setPostazioneId(String postazioneId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_postazioneId = postazioneId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Prenotazioni.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Prenotazioni.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Prenotazioni toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Prenotazioni>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PrenotazioniImpl prenotazioniImpl = new PrenotazioniImpl();

		prenotazioniImpl.setUuid(getUuid());
		prenotazioniImpl.setPrenotazioneId(getPrenotazioneId());
		prenotazioniImpl.setGroupId(getGroupId());
		prenotazioniImpl.setCompanyId(getCompanyId());
		prenotazioniImpl.setUserId(getUserId());
		prenotazioniImpl.setUserName(getUserName());
		prenotazioniImpl.setCreateDate(getCreateDate());
		prenotazioniImpl.setModifiedDate(getModifiedDate());
		prenotazioniImpl.setEmail(getEmail());
		prenotazioniImpl.setData(getData());
		prenotazioniImpl.setOraInizio(getOraInizio());
		prenotazioniImpl.setOraFine(getOraFine());
		prenotazioniImpl.setPostazioneId(getPostazioneId());

		prenotazioniImpl.resetOriginalValues();

		return prenotazioniImpl;
	}

	@Override
	public Prenotazioni cloneWithOriginalValues() {
		PrenotazioniImpl prenotazioniImpl = new PrenotazioniImpl();

		prenotazioniImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		prenotazioniImpl.setPrenotazioneId(
			this.<Long>getColumnOriginalValue("prenotazioneId"));
		prenotazioniImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		prenotazioniImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		prenotazioniImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		prenotazioniImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		prenotazioniImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		prenotazioniImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		prenotazioniImpl.setEmail(this.<String>getColumnOriginalValue("email"));
		prenotazioniImpl.setData(this.<Date>getColumnOriginalValue("data_"));
		prenotazioniImpl.setOraInizio(
			this.<String>getColumnOriginalValue("oraInizio"));
		prenotazioniImpl.setOraFine(
			this.<String>getColumnOriginalValue("oraFine"));
		prenotazioniImpl.setPostazioneId(
			this.<String>getColumnOriginalValue("postazioneId"));

		return prenotazioniImpl;
	}

	@Override
	public int compareTo(Prenotazioni prenotazioni) {
		long primaryKey = prenotazioni.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Prenotazioni)) {
			return false;
		}

		Prenotazioni prenotazioni = (Prenotazioni)object;

		long primaryKey = prenotazioni.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Prenotazioni> toCacheModel() {
		PrenotazioniCacheModel prenotazioniCacheModel =
			new PrenotazioniCacheModel();

		prenotazioniCacheModel.uuid = getUuid();

		String uuid = prenotazioniCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			prenotazioniCacheModel.uuid = null;
		}

		prenotazioniCacheModel.prenotazioneId = getPrenotazioneId();

		prenotazioniCacheModel.groupId = getGroupId();

		prenotazioniCacheModel.companyId = getCompanyId();

		prenotazioniCacheModel.userId = getUserId();

		prenotazioniCacheModel.userName = getUserName();

		String userName = prenotazioniCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			prenotazioniCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			prenotazioniCacheModel.createDate = createDate.getTime();
		}
		else {
			prenotazioniCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			prenotazioniCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			prenotazioniCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		prenotazioniCacheModel.email = getEmail();

		String email = prenotazioniCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			prenotazioniCacheModel.email = null;
		}

		Date data = getData();

		if (data != null) {
			prenotazioniCacheModel.data = data.getTime();
		}
		else {
			prenotazioniCacheModel.data = Long.MIN_VALUE;
		}

		prenotazioniCacheModel.oraInizio = getOraInizio();

		String oraInizio = prenotazioniCacheModel.oraInizio;

		if ((oraInizio != null) && (oraInizio.length() == 0)) {
			prenotazioniCacheModel.oraInizio = null;
		}

		prenotazioniCacheModel.oraFine = getOraFine();

		String oraFine = prenotazioniCacheModel.oraFine;

		if ((oraFine != null) && (oraFine.length() == 0)) {
			prenotazioniCacheModel.oraFine = null;
		}

		prenotazioniCacheModel.postazioneId = getPostazioneId();

		String postazioneId = prenotazioniCacheModel.postazioneId;

		if ((postazioneId != null) && (postazioneId.length() == 0)) {
			prenotazioniCacheModel.postazioneId = null;
		}

		return prenotazioniCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Prenotazioni, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Prenotazioni, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Prenotazioni, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Prenotazioni)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Prenotazioni>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Prenotazioni.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _prenotazioneId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _email;
	private Date _data;
	private String _oraInizio;
	private String _oraFine;
	private String _postazioneId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Prenotazioni, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Prenotazioni)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("prenotazioneId", _prenotazioneId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("data_", _data);
		_columnOriginalValues.put("oraInizio", _oraInizio);
		_columnOriginalValues.put("oraFine", _oraFine);
		_columnOriginalValues.put("postazioneId", _postazioneId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("data_", "data");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("prenotazioneId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("email", 256L);

		columnBitmasks.put("data_", 512L);

		columnBitmasks.put("oraInizio", 1024L);

		columnBitmasks.put("oraFine", 2048L);

		columnBitmasks.put("postazioneId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Prenotazioni _escapedModel;

}