/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazione.model.impl;

import prenotazione.model.Prenotazione;

import prenotazione.service.PrenotazioneLocalServiceUtil;

/**
 * The extended model base implementation for the Prenotazione service. Represents a row in the &quot;Prenotazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PrenotazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PrenotazioneImpl
 * @see Prenotazione
 * @generated
 */
public abstract class PrenotazioneBaseImpl
	extends PrenotazioneModelImpl implements Prenotazione {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prenotazione model instance should use the <code>Prenotazione</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PrenotazioneLocalServiceUtil.addPrenotazione(this);
		}
		else {
			PrenotazioneLocalServiceUtil.updatePrenotazione(this);
		}
	}

}