/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazione.model.impl;

import prenotazione.model.Ruolo;

import prenotazione.service.RuoloLocalServiceUtil;

/**
 * The extended model base implementation for the Ruolo service. Represents a row in the &quot;ruoli&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RuoloImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RuoloImpl
 * @see Ruolo
 * @generated
 */
public abstract class RuoloBaseImpl extends RuoloModelImpl implements Ruolo {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ruolo model instance should use the <code>Ruolo</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RuoloLocalServiceUtil.addRuolo(this);
		}
		else {
			RuoloLocalServiceUtil.updateRuolo(this);
		}
	}

}