/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazione.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Postazione service. Represents a row in the &quot;postazioni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>prenotazione.model.impl.PostazioneModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>prenotazione.model.impl.PostazioneImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Postazione
 * @generated
 */
@ProviderType
public interface PostazioneModel extends BaseModel<Postazione> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a postazione model instance should use the {@link Postazione} interface instead.
	 */

	/**
	 * Returns the primary key of this postazione.
	 *
	 * @return the primary key of this postazione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this postazione.
	 *
	 * @param primaryKey the primary key of this postazione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the postazione ID of this postazione.
	 *
	 * @return the postazione ID of this postazione
	 */
	public long getPostazioneId();

	/**
	 * Sets the postazione ID of this postazione.
	 *
	 * @param postazioneId the postazione ID of this postazione
	 */
	public void setPostazioneId(long postazioneId);

	/**
	 * Returns the stanza ID of this postazione.
	 *
	 * @return the stanza ID of this postazione
	 */
	public long getStanzaId();

	/**
	 * Sets the stanza ID of this postazione.
	 *
	 * @param stanzaId the stanza ID of this postazione
	 */
	public void setStanzaId(long stanzaId);

	/**
	 * Returns the nome postazione of this postazione.
	 *
	 * @return the nome postazione of this postazione
	 */
	@AutoEscape
	public String getNomePostazione();

	/**
	 * Sets the nome postazione of this postazione.
	 *
	 * @param nomePostazione the nome postazione of this postazione
	 */
	public void setNomePostazione(String nomePostazione);

	@Override
	public Postazione cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}