/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazione.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Prenotazioni service. Represents a row in the &quot;Prenotazioni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>prenotazione.model.impl.PrenotazioniModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>prenotazione.model.impl.PrenotazioniImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Prenotazioni
 * @generated
 */
@ProviderType
public interface PrenotazioniModel
	extends BaseModel<Prenotazioni>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a prenotazioni model instance should use the {@link Prenotazioni} interface instead.
	 */

	/**
	 * Returns the primary key of this prenotazioni.
	 *
	 * @return the primary key of this prenotazioni
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this prenotazioni.
	 *
	 * @param primaryKey the primary key of this prenotazioni
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this prenotazioni.
	 *
	 * @return the uuid of this prenotazioni
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this prenotazioni.
	 *
	 * @param uuid the uuid of this prenotazioni
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the prenotazione ID of this prenotazioni.
	 *
	 * @return the prenotazione ID of this prenotazioni
	 */
	public long getPrenotazioneId();

	/**
	 * Sets the prenotazione ID of this prenotazioni.
	 *
	 * @param prenotazioneId the prenotazione ID of this prenotazioni
	 */
	public void setPrenotazioneId(long prenotazioneId);

	/**
	 * Returns the group ID of this prenotazioni.
	 *
	 * @return the group ID of this prenotazioni
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this prenotazioni.
	 *
	 * @param groupId the group ID of this prenotazioni
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this prenotazioni.
	 *
	 * @return the company ID of this prenotazioni
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this prenotazioni.
	 *
	 * @param companyId the company ID of this prenotazioni
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this prenotazioni.
	 *
	 * @return the user ID of this prenotazioni
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this prenotazioni.
	 *
	 * @param userId the user ID of this prenotazioni
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this prenotazioni.
	 *
	 * @return the user uuid of this prenotazioni
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this prenotazioni.
	 *
	 * @param userUuid the user uuid of this prenotazioni
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this prenotazioni.
	 *
	 * @return the user name of this prenotazioni
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this prenotazioni.
	 *
	 * @param userName the user name of this prenotazioni
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this prenotazioni.
	 *
	 * @return the create date of this prenotazioni
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this prenotazioni.
	 *
	 * @param createDate the create date of this prenotazioni
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this prenotazioni.
	 *
	 * @return the modified date of this prenotazioni
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this prenotazioni.
	 *
	 * @param modifiedDate the modified date of this prenotazioni
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email of this prenotazioni.
	 *
	 * @return the email of this prenotazioni
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this prenotazioni.
	 *
	 * @param email the email of this prenotazioni
	 */
	public void setEmail(String email);

	/**
	 * Returns the data of this prenotazioni.
	 *
	 * @return the data of this prenotazioni
	 */
	public Date getData();

	/**
	 * Sets the data of this prenotazioni.
	 *
	 * @param data the data of this prenotazioni
	 */
	public void setData(Date data);

	/**
	 * Returns the ora inizio of this prenotazioni.
	 *
	 * @return the ora inizio of this prenotazioni
	 */
	@AutoEscape
	public String getOraInizio();

	/**
	 * Sets the ora inizio of this prenotazioni.
	 *
	 * @param oraInizio the ora inizio of this prenotazioni
	 */
	public void setOraInizio(String oraInizio);

	/**
	 * Returns the ora fine of this prenotazioni.
	 *
	 * @return the ora fine of this prenotazioni
	 */
	@AutoEscape
	public String getOraFine();

	/**
	 * Sets the ora fine of this prenotazioni.
	 *
	 * @param oraFine the ora fine of this prenotazioni
	 */
	public void setOraFine(String oraFine);

	/**
	 * Returns the postazione ID of this prenotazioni.
	 *
	 * @return the postazione ID of this prenotazioni
	 */
	@AutoEscape
	public String getPostazioneId();

	/**
	 * Sets the postazione ID of this prenotazioni.
	 *
	 * @param postazioneId the postazione ID of this prenotazioni
	 */
	public void setPostazioneId(String postazioneId);

	@Override
	public Prenotazioni cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}