/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazione.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ruolo service. Represents a row in the &quot;ruoli&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>prenotazione.model.impl.RuoloModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>prenotazione.model.impl.RuoloImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ruolo
 * @generated
 */
@ProviderType
public interface RuoloModel extends BaseModel<Ruolo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ruolo model instance should use the {@link Ruolo} interface instead.
	 */

	/**
	 * Returns the primary key of this ruolo.
	 *
	 * @return the primary key of this ruolo
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ruolo.
	 *
	 * @param primaryKey the primary key of this ruolo
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this ruolo.
	 *
	 * @return the ID of this ruolo
	 */
	public int getId();

	/**
	 * Sets the ID of this ruolo.
	 *
	 * @param id the ID of this ruolo
	 */
	public void setId(int id);

	/**
	 * Returns the nome of this ruolo.
	 *
	 * @return the nome of this ruolo
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this ruolo.
	 *
	 * @param nome the nome of this ruolo
	 */
	public void setNome(String nome);

	/**
	 * Returns the descrizione of this ruolo.
	 *
	 * @return the descrizione of this ruolo
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this ruolo.
	 *
	 * @param descrizione the descrizione of this ruolo
	 */
	public void setDescrizione(String descrizione);

	@Override
	public Ruolo cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}