/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazione.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Utente service. Represents a row in the &quot;utenti&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>prenotazione.model.impl.UtenteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>prenotazione.model.impl.UtenteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Utente
 * @generated
 */
@ProviderType
public interface UtenteModel extends BaseModel<Utente> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a utente model instance should use the {@link Utente} interface instead.
	 */

	/**
	 * Returns the primary key of this utente.
	 *
	 * @return the primary key of this utente
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this utente.
	 *
	 * @param primaryKey the primary key of this utente
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this utente.
	 *
	 * @return the ID of this utente
	 */
	public long getId();

	/**
	 * Sets the ID of this utente.
	 *
	 * @param id the ID of this utente
	 */
	public void setId(long id);

	/**
	 * Returns the nome of this utente.
	 *
	 * @return the nome of this utente
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this utente.
	 *
	 * @param nome the nome of this utente
	 */
	public void setNome(String nome);

	/**
	 * Returns the cognome of this utente.
	 *
	 * @return the cognome of this utente
	 */
	@AutoEscape
	public String getCognome();

	/**
	 * Sets the cognome of this utente.
	 *
	 * @param cognome the cognome of this utente
	 */
	public void setCognome(String cognome);

	/**
	 * Returns the email of this utente.
	 *
	 * @return the email of this utente
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this utente.
	 *
	 * @param email the email of this utente
	 */
	public void setEmail(String email);

	/**
	 * Returns the password of this utente.
	 *
	 * @return the password of this utente
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this utente.
	 *
	 * @param password the password of this utente
	 */
	public void setPassword(String password);

	/**
	 * Returns the percorso foto of this utente.
	 *
	 * @return the percorso foto of this utente
	 */
	@AutoEscape
	public String getPercorsoFoto();

	/**
	 * Sets the percorso foto of this utente.
	 *
	 * @param percorsoFoto the percorso foto of this utente
	 */
	public void setPercorsoFoto(String percorsoFoto);

	/**
	 * Returns the anno assunzione of this utente.
	 *
	 * @return the anno assunzione of this utente
	 */
	public Date getAnnoAssunzione();

	/**
	 * Sets the anno assunzione of this utente.
	 *
	 * @param annoAssunzione the anno assunzione of this utente
	 */
	public void setAnnoAssunzione(Date annoAssunzione);

	@Override
	public Utente cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}