/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package prenotazioni.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Prenotazione service. Represents a row in the &quot;prenotazioni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>prenotazioni.model.impl.PrenotazioneModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>prenotazioni.model.impl.PrenotazioneImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Prenotazione
 * @generated
 */
@ProviderType
public interface PrenotazioneModel extends BaseModel<Prenotazione> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a prenotazione model instance should use the {@link Prenotazione} interface instead.
	 */

	/**
	 * Returns the primary key of this prenotazione.
	 *
	 * @return the primary key of this prenotazione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this prenotazione.
	 *
	 * @param primaryKey the primary key of this prenotazione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this prenotazione.
	 *
	 * @return the ID of this prenotazione
	 */
	public long getId();

	/**
	 * Sets the ID of this prenotazione.
	 *
	 * @param id the ID of this prenotazione
	 */
	public void setId(long id);

	/**
	 * Returns the data of this prenotazione.
	 *
	 * @return the data of this prenotazione
	 */
	public Date getData();

	/**
	 * Sets the data of this prenotazione.
	 *
	 * @param data the data of this prenotazione
	 */
	public void setData(Date data);

	/**
	 * Returns the ora inizio of this prenotazione.
	 *
	 * @return the ora inizio of this prenotazione
	 */
	public Date getOraInizio();

	/**
	 * Sets the ora inizio of this prenotazione.
	 *
	 * @param oraInizio the ora inizio of this prenotazione
	 */
	public void setOraInizio(Date oraInizio);

	/**
	 * Returns the ora fine of this prenotazione.
	 *
	 * @return the ora fine of this prenotazione
	 */
	public Date getOraFine();

	/**
	 * Sets the ora fine of this prenotazione.
	 *
	 * @param oraFine the ora fine of this prenotazione
	 */
	public void setOraFine(Date oraFine);

	/**
	 * Returns the utenti ID of this prenotazione.
	 *
	 * @return the utenti ID of this prenotazione
	 */
	public long getUtentiId();

	/**
	 * Sets the utenti ID of this prenotazione.
	 *
	 * @param utentiId the utenti ID of this prenotazione
	 */
	public void setUtentiId(long utentiId);

	/**
	 * Returns the postazione ID of this prenotazione.
	 *
	 * @return the postazione ID of this prenotazione
	 */
	public long getPostazioneId();

	/**
	 * Sets the postazione ID of this prenotazione.
	 *
	 * @param postazioneId the postazione ID of this prenotazione
	 */
	public void setPostazioneId(long postazioneId);

	@Override
	public Prenotazione cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}